### ISSUE TITLE
Where is OmniFocus JavaScript for Automation (JXA) Library?

### ISSUE THREAD

**Issue by JMichaelTX** [brandonpittman/OmniFocus#12]
Hi Brandon (@brandonpittman),
Can you please provide a link to the JXA script library you previously published for OmniFocus?
I much prefer JXA over AppleScript, and would like to use it.

I realize it is depreciated now, but it would still be helpful to me.
Thanks.

You wrote:

> I had previously written an OmniFocus library using JavaScript for Automation, but it’s got issues that vanilla AppleScript does not.

**Comment by brandonpittman** [comment]
It's in the deprecated scripts folder. 

Best regards,

Brandon Pittman

**Comment by JMichaelTX** [comment]
Brandon, thanks for the very quick response.  I found the JXA lib.

You said previously that "it's got issues".  Would you mind listing these issues?

**Comment by brandonpittman** [comment]
You can't use it with vanilla AppleScript. You also can't work with OmniFocus' frequency rules in JXA. Or at least you couldn't as of last year when I moved away from JXA. 

Best regards,

Brandon Pittman
