### ISSUE TITLE
Coercing error in OmniFocus Pomodoro script (OmniFocus 3)

### ISSUE THREAD

**Issue by tacotuesday** [brandonpittman/OmniFocus#13]
![of_pomodoro_error](https://user-images.githubusercontent.com/1495452/81061914-2d5b6800-8ea3-11ea-9c29-d530ddd910d7.jpg)

I get an execution error on two different machines when trying to use the OmniFocus Pomodoro script:

`Can't make <<class FCdw>> id 25335 of <<class FCDo>> into type integer. (-1700)` I am unfamiliar with AppleScript: is there a solution to this?

**Comment by brandonpittman** [comment]
I wrote all those scripts for OmniFocus 2. It’s possible OF3 broke the API 2 had for AppleScript.

**Comment by tacotuesday** [comment]
Okay, no problem. I'll try to dig into it.
