### ISSUE TITLE
Function documentation

### ISSUE THREAD

**Issue by Mxchaeltrxn** [brandonpittman/OmniFocus#15]
Hi. I have looked at the readme and the website but I could not find much information on the functions and what they do. They do not all seem intuitive to me (but maybe that is because I have not written applescripts for OmniFocus before. 

Do you think I should be looking somewhere else for this information or do you think I'll be fine once I get started?

Thanks

**Comment by brandonpittman** [comment]
@Mxchaeltrxn I'd just read through the source code to see what they do. The JXA version even has JSDoc annotations.

I have no intention of writing further documentation on a per-function basis.
