### ISSUE TITLE
it doesn't work 

### ISSUE THREAD

**Issue by shiren** [brandonpittman/OmniFocus#5]
![2015-08-07 4 51 58](https://cloud.githubusercontent.com/assets/389021/9131214/ad9e59bc-3d24-11e5-834b-67ffa72808e5.png)

keep error occur.

I think it should be omnifocus issue

**Comment by allensong** [comment]
Try this:

of = Library('OmniFocus')
sel = of.selected()
app = Application('OmniFocus')
app.includeStandardAdditions = true
	
	today = new Date
    today.setHours(21)
    today.setMinutes(00)
    of.setDefer(sel, today)

Run it in OmniFocus js folder

**Comment by brandonpittman** [comment]
![screen shot 2015-08-08 at 4 49 37 pm](https://cloud.githubusercontent.com/assets/967145/9152219/89f7d956-3ded-11e5-9e63-c04f187996b8.png)

Not a problem with the library.

**Comment by shiren** [comment]
yep it works well~
