### ISSUE TITLE
Hierarchical contexts

### ISSUE THREAD

**Issue by plessl** [brandonpittman/OmniFocus#9]
I'm trying to manage delegated tasks in OmniFocus by adding a "delegated" context and sub-contexts "Alice", "Bob", etc. for each person to which I'm delegating a task. My objective is to write a script to send to each person a reminder with a list with delegated jobs by email.

In my tests I was not able to recognize that "Alice" is a sub-context of "delegated". This is, when querying the context for a task "Demo" with context "Delegated : Alice" task.context.name() returns just "Alice" but not the parent "Delegated".

Is there a way to access the hierarchy of contexts?

**Comment by brandonpittman** [comment]
~~~js
of = Library('OmniFocus')
sel = of.selected()
app = Application('OmniFocus')
app.includeStandardAdditions = true

of.getContext('Alice').container()
~~~

This would return the "Delegated" context.
